// KT Companion - Fight UI stable v0.0.8.2
(function(){
function ensure(){if(document.getElementById('fight'))return;const nav=document.querySelector('nav'),main=document.querySelector('main');if(!nav||!main)return;const b=document.createElement('button');b.className='tab';b.dataset.p='fight';b.textContent='⚔️ Lucha';nav.appendChild(b);const s=document.createElement('section');s.id='fight';s.className='page';s.innerHTML='<div class="grid"><div class="card"><h2>⚔️ Atacante</h2><div id="fightAName" class="notice">Sin arma seleccionada</div><div class="row"><div><label>Ataques</label><input id="fa" type="number" min="1" value="5"></div><div><label>Impacta con</label><select id="fh"><option>2</option><option selected>3</option><option>4</option><option>5</option></select></div></div><div class="row"><div><label>Daño normal</label><input id="fad" type="number" value="4"></div><div><label>Daño crítico</label><input id="facd" type="number" value="6"></div></div></div><div class="card"><h2>🛡️ Defensor</h2><div id="fightDName" class="notice">Sin arma seleccionada</div><div class="row"><div><label>Ataques del arma CaC</label><input id="fda" type="number" min="1" value="4"></div><div><label>Impacta con</label><select id="fdh"><option>2</option><option>3</option><option selected>4</option><option>5</option></select></div></div><div class="row"><div><label>Daño normal</label><input id="fdd" type="number" value="3"></div><div><label>Daño crítico</label><input id="fdcd" type="number" value="4"></div></div></div></div><div class="card"><h2>🎲 Lucha</h2><p>Los éxitos se resuelven <b>dado a dado</b>. Cada combatiente puede golpear o anular un éxito rival.</p><div class="actions"><button class="primary" onclick="fightRoll()">🎲 Simular lucha</button><button onclick="clearFight()">Limpiar</button></div><div id="fightResult" class="rollbox">Selecciona un arma CaC de cada combatiente.</div></div>';main.appendChild(s);b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));s.classList.add('active');};}
function melee(w){const n=(w[0]||'').toLowerCase();if(/pistol|rifle|bolter|carbine|gun|launcher|grenade|cannon|incinerator|melta|sniper|bolt thrower/.test(n))return false;return /blade|sword|fist|hammer|maul|claw|fang|knife|stave|weapon|chainsword|combat|shield|staff|axe|spear|talon|gauntlet|scythe|klaw|glaive|flail|whip/.test(n);}
function setSide(side,op,w){ensure();const p=side==='a'?'fightAName':'fightDName';document.getElementById(p).innerHTML='<b>'+op+' · '+w[0]+'</b><div class="tag">'+w[1]+' ataques · '+w[2]+'+ · '+w[3]+'/'+w[4]+' · '+(w[5]||'')+'</div>';if(side==='a'){fa.value=w[1];fh.value=w[2];fad.value=w[3];facd.value=w[4];window.fightA={op:op,w:w};}else{fda.value=w[1];fdh.value=w[2];fdd.value=w[3];fdcd.value=w[4];window.fightD={op:op,w:w};}document.querySelector('[data-p="fight"]').click();}
window.clearFight=function(){window.fightA=null;window.fightD=null;document.getElementById('fightAName').textContent='Sin arma seleccionada';document.getElementById('fightDName').textContent='Sin arma seleccionada';};
window.fightRoll=function(){const a=window.fightA,d=window.fightD;if(!a||!d){fightResult.innerHTML='<b>Selecciona las dos armas CaC.</b>';return;}const roll=n=>Array.from({length:n},()=>1+Math.floor(Math.random()*6));const ar=roll(a.w[1]),dr=roll(d.w[1]),ae=ar.filter(x=>x>=a.w[2]),de=dr.filter(x=>x>=d.w[2]);let A=ae.map(x=>({v:x,c:x===6})),D=de.map(x=>({v:x,c:x===6})),log=[];while(A.length||D.length){if(A.length){const i=A.findIndex(x=>x.c),x=A.splice(i>=0?i:0,1)[0];log.push('⚔️ '+a.op+' · '+a.w[0]+' → '+x.v+(x.c?' ⭐':'')+' → GOLPEAR / ANULAR');}if(D.length){const i=D.findIndex(x=>x.c),x=D.splice(i>=0?i:0,1)[0];log.push('🛡️ '+d.op+' · '+d.w[0]+' → '+x.v+(x.c?' ⭐':'')+' → GOLPEAR / ANULAR');}}fightResult.innerHTML='<h3>🎲 Secuencia</h3><div>'+log.map(x=>'<div style="padding:5px 0;border-bottom:1px solid var(--line)">'+x+'</div>').join('')+'</div>';};
function decorate(){ensure();const t=window.teams&&window.teams[$('army').value];if(!t)return;const o=t[+$('op').value];document.querySelectorAll('#opcard .weapon').forEach((el,i)=>{const w=o[4][i];if(!melee(w))return;const box=el.querySelector('.actions');if(!box)return;if(!box.querySelector('.fightbtn')){const b=document.createElement('button');b.className='fightbtn';b.textContent='⚔️ Añadir a lucha';b.onclick=()=>setSide('a',o[0],w);box.appendChild(b);}if(!box.querySelector('.fightdefbtn')){const d=document.createElement('button');d.className='fightdefbtn';d.textContent='🛡️ Añadir como defensor';d.onclick=()=>setSide('d',o[0],w);box.appendChild(d);}});}
ensure();const old=window.renderOp;if(old&&!old.__fightWrapped){window.renderOp=function(){old();setTimeout(decorate,0);};window.renderOp.__fightWrapped=true;setTimeout(decorate,100);}else setTimeout(decorate,100);
})();
