// KT Companion - Fight prototype v0.0.8.1
(function(){
  const isMelee=n=>/chainsword|power weapon|power fist|thunder hammer|fists|combat knife|combat blade|xenophase|fangs|power maul|storm shield|heavy thunder hammer|blade|claw|fang|knife|stave|weapon|sword|hammer|maul|scythe|choppa|klaw|gauntlet|sickle|glaive|wrench|flail|whip|axe/i.test(n)&&!/grenade launcher|bolt rifle|bolt pistol|plasma pistol|heavy bolter|bolter|carbine|rifle|cannon|incinerator|launcher|sniper|melta|pistol|flame|focused bolt|sweeping bolt/i.test(n);
  function ensure(){
    const nav=document.querySelector('nav'); if(!nav)return;
    let b=document.querySelector('.tab[data-p="fight"]');
    if(!b){b=document.createElement('button');b.className='tab';b.dataset.p='fight';b.textContent='⚔️ Lucha';nav.appendChild(b);}
    let s=document.getElementById('fight');
    if(!s){s=document.createElement('section');s.id='fight';s.className='page';s.innerHTML=`<div class="grid"><div class="card"><h2>⚔️ Atacante</h2><div id="fightAName"><span class="tag">Sin arma seleccionada</span></div><div class="row"><div><label>Dados de ataque</label><input id="fa" type="number" min="1" max="20" value="5"></div><div><label>Impacta con</label><select id="fh"><option>2</option><option selected>3</option><option>4</option><option>5</option></select></div></div><div class="row"><div><label>Daño normal</label><input id="fd" type="number" value="4"></div><div><label>Daño crítico</label><input id="fcd" type="number" value="6"></div></div></div><div class="card"><h2>🛡️ Defensor</h2><div id="fightDName"><span class="tag">Sin arma seleccionada</span></div><div class="row"><div><label>Dados de combate</label><input id="fda" type="number" min="1" max="20" value="4"></div><div><label>Impacta con</label><select id="fdh"><option>2</option><option>3</option><option selected>4</option><option>5</option></select></div></div><div class="row"><div><label>Daño normal</label><input id="fdd" type="number" value="3"></div><div><label>Daño crítico</label><input id="fdcd" type="number" value="4"></div></div></div></div><div class="card"><h2>📊 Calculadora de lucha</h2><p class="muted">El nombre y el perfil del arma seleccionada se conservan al pasarla a lucha. La defensa usa los ataques del arma CaC del defensor.</p><div class="actions"><button class="primary" onclick="fightCalc()">📊 Calcular lucha</button><button onclick="fightRoll()">🎲 Simular lucha</button></div><div id="fightResult" class="rollbox">Selecciona un arma CaC.</div></div>`;document.querySelector('main').appendChild(s)}
    b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));s.classList.add('active')};
  }
  function setA(w,op){ensure();fightAName.innerHTML='<b>'+op+' · '+w[0]+'</b><div class="tag">'+w[1]+' ataques · '+w[2]+'+ · '+w[3]+'/'+w[4]+' · '+(w[5]||'')+'</div>';fa.value=w[1];fh.value=w[2];fd.value=w[3];fcd.value=w[4];window.fightA={op,w};document.querySelector('.tab[data-p="fight"]').click()}
  function setD(w,op){ensure();fightDName.innerHTML='<b>'+op+' · '+w[0]+'</b><div class="tag">'+w[1]+' dados · '+w[2]+'+ · '+w[3]+'/'+w[4]+' · '+(w[5]||'')+'</div>';fda.value=w[1];fdh.value=w[2];fdd.value=w[3];fdcd.value=w[4];window.fightD={op,w};document.querySelector('.tab[data-p="fight"]').click()}
  window.fightSelectAttacker=i=>{const t=teams[$('army').value]||teams.aod,o=t[+$('op').value],w=o[4][i];if(isMelee(w))setA(w,o[0])};
  window.fightSelectDefender=i=>{const t=teams[$('army').value]||teams.aod,o=t[+$('op').value],w=o[4][i];if(isMelee(w))setD(w,o[0])};
  window.fightCalc=()=>{if(!fightA||!fightD){fightResult.innerHTML='<b>Selecciona las dos armas CaC.</b>';return}fightResult.innerHTML='<b>'+fightA.op+' · '+fightA.w[0]+'</b> ⚔️ VS ⚔️ <b>'+fightD.op+' · '+fightD.w[0]+'</b><br><br>Atacante: '+fightA.w[1]+' dados · '+fightA.w[2]+'+ · '+fightA.w[3]+'/'+fightA.w[4]+'<br>Defensor: '+fightD.w[1]+' dados · '+fightD.w[2]+'+ · '+fightD.w[3]+'/'+fightD.w[4]+'<br><br><span class="tag">Motor de lucha en prueba.</span>};
  window.fightRoll=()=>{if(!fightA||!fightD){fightResult.innerHTML='<b>Selecciona las dos armas CaC.</b>';return}const r=n=>Array.from({length:n},()=>1+Math.floor(Math.random()*6)).sort((a,b)=>b-a),a=r(fightA.w[1]),d=r(fightD.w[1]),ae=a.filter(x=>x>=fightA.w[2]),de=d.filter(x=>x>=fightD.w[2]);fightResult.innerHTML='<b>'+fightA.op+' · '+fightA.w[0]+'</b><br>🎲 '+a.join(' · ')+'<br>Éxitos: '+ae.length+' · Críticos: '+ae.filter(x=>x===6).length+'<hr><b>'+fightD.op+' · '+fightD.w[0]+'</b><br>🎲 '+d.join(' · ')+'<br>Éxitos: '+de.length+' · Críticos: '+de.filter(x=>x===6).length};
  function decorate(){ensure();document.querySelectorAll('#opcard .weapon').forEach((el,i)=>{const title=el.querySelector('b');if(!title||!isMelee(title.textContent))return;const box=el.querySelector('.actions');if(!box||box.querySelector('.fightbtn'))return;const b=document.createElement('button');b.className='fightbtn';b.textContent='⚔️ Usar en lucha';b.onclick=()=>fightSelectAttacker(i);box.appendChild(b)})}
  const old=window.renderOp;window.renderOp=function(){if(old)old();setTimeout(decorate,0)};
  ensure();setTimeout(decorate,0);
})();