/* KT Companion — TAC OP + OPERACIÓN PRIMARIA */
(function(){
 const frame=()=>document.getElementById('game'); const doc=()=>frame()?.contentDocument||null; const win=()=>frame()?.contentWindow||null;
 const branches=[['1. INFILTRACIÓN',['1a. Robar información','1b. Localizar enemigo','1c. Colocar dispositivos']],['2. SEGURIDAD',['2a. Mártires','2b. El mensajero','2c. Izar bandera']],['3. RECONOCIMIENTO',['3a. Recuperar','3b. Vigilar el movimiento enemigo','3c. Flanco']],['4. BUSCAR Y DESTRUIR',['4a. Hacer huir','4b. Revisar y purgar','4c. Dominación']]]; const primary=['OP TAC','OP ASESINATO','OP CRIT'];
 function side(){const d=doc();return d?.querySelector('#sideTabs .side.active')?.textContent.includes('RIVAL')?'enemy':'friend'}
 function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function render(){const d=doc(),w=win();if(!d||!d.getElementById('ops'))return false;let host=d.getElementById('ktTacOps');if(!host){host=d.createElement('div');host.id='ktTacOps';host.className='card';const actions=d.querySelector('#s3 .actions');d.getElementById('ops').parentElement.insertBefore(host,actions||null)}const s=side(),st=w.__ktTacOpState||(w.__ktTacOpState={friend:{tac:'',primary:''},enemy:{tac:'',primary:''}});host.innerHTML='<h3>5. Operación táctica (TAC OP)</h3><div class="summary">Escoge individualmente una sola TAC OP para cada jugador.</div><div class="tacgrid">'+branches.map(b=>'<div class="tacbranch"><div class="tactitle">'+esc(b[0])+'</div>'+b[1].map(o=>'<label class="tacchoice"><input type="radio" name="tacop-'+s+'" value="'+esc(o)+'"><span>'+esc(o)+'</span></label>').join('')+'</div>').join('')+'</div><h3 style="margin-top:18px">6. Operación primaria</h3><div class="primaryops">'+primary.map(o=>'<label class="tacchoice"><input type="radio" name="primaryop-'+s+'" value="'+esc(o)+'"><span>'+esc(o)+'</span></label>').join('')+'</div>';if(st[s].tac){const x=[...host.querySelectorAll('input[name="tacop-'+s+'"]')].find(i=>i.value===st[s].tac);if(x)x.checked=true}if(st[s].primary){const x=[...host.querySelectorAll('input[name="primaryop-'+s+'"]')].find(i=>i.value===st[s].primary);if(x)x.checked=true}host.querySelectorAll('input').forEach(i=>i.addEventListener('change',()=>{if(i.name==='tacop-'+s)st[s].tac=i.value;if(i.name==='primaryop-'+s)st[s].primary=i.value}));return true}
 function install(){const d=doc(),w=win();if(!d||!w||!d.getElementById('ops'))return;if(!w.__ktTacInstalled){w.__ktTacInstalled=true;w.__ktTacOpState={friend:{tac:'',primary:''},enemy:{tac:'',primary:''}};const orig=w.switchSide;if(typeof orig==='function')w.switchSide=function(s){const r=orig.apply(this,arguments);setTimeout(render,0);return r}}render()}
 const oldSave=window.saveGame;window.saveGame=function(){oldSave?.();setTimeout(()=>{try{const st=win()?.__ktTacOpState||{friend:{tac:'',primary:''},enemy:{tac:'',primary:''}},key='kt_companion_matrices_pdf2',a=JSON.parse(localStorage.getItem(key)||'[]');if(a[0]){a[0].tacOps={friend:st.friend,enemy:st.enemy};localStorage.setItem(key,JSON.stringify(a));window.showSaved?.()}}catch(e){console.error(e)}},80)};
 const oldShow=window.showSaved;window.showSaved=function(){oldShow?.();setTimeout(()=>{try{const a=JSON.parse(localStorage.getItem('kt_companion_matrices_pdf2')||'[]'),cards=document.querySelectorAll('#savedList .card');a.forEach((s,i)=>{if(!cards[i]||!s.tacOps)return;const f=s.tacOps.friend||{},r=s.tacOps.enemy||{},div=document.createElement('div');div.className='tacsaved';div.innerHTML='<p><b>🎯 Operación táctica:</b> 🟢 '+esc(f.tac||'Ninguna')+(s.enemy?' · 🔴 '+esc(r.tac||'Ninguna'):'')+'</p><p><b>🏁 Operación primaria:</b> 🟢 '+esc(f.primary||'Ninguna')+(s.enemy?' · 🔴 '+esc(r.primary||'Ninguna'):'')+'</p>';cards[i].insertBefore(div,cards[i].querySelector('details')||null)})}catch(e){console.error(e)}},40)};
 const f=frame();if(f)f.addEventListener('load',()=>setTimeout(install,100));setTimeout(install,500);setTimeout(install,1200);
})();