const app=document.getElementById('app');
const phases=['despliegue','turno1','turno2','turno3','turno4'];
const labels={despliegue:'DESPLIEGUE',turno1:'TURNO 1',turno2:'TURNO 2',turno3:'TURNO 3',turno4:'TURNO 4'};
const teams=[['aod','Angels of Death'],['plague','Plague Marines'],['demo','Kill Team de prueba']];
const maps=[['m1','Mapa de prueba 01'],['m2','Mapa de prueba 02'],['m3','Mapa de prueba 03']];
const ops=['Eliminar al líder enemigo','Controlar un objetivo','Realizar una acción de misión','Mantener una posición','Conservar un operativo clave','Negar un objetivo','Sobrevivir con un especialista','Conseguir ventaja de posición','Ejecutar la misión'];
const S={screen:'home',step:1,team:null,map:null,critical:null,phase:'despliegue',phaseData:{},objects:[],notes:'',matrixId:null,matrixName:'',tool:'select',color:'#ef5a16',opacity:1,tokenMm:28,undo:[],redo:[]};
let canvas,ctx,down=false,start=null,selected=null,preview=null;
const copy=v=>JSON.parse(JSON.stringify(v));
const esc=s=>String(s||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function header(){return `<header class="header"><div class="brand"><img src="../icon-512.png"><div><b>KILL TEAM COMPANION</b><small>ALPHA</small></div></div><button onclick="home()">INICIO</button></header>`}
function home(){S.screen='home';app.innerHTML=header()+`<main class="menu"><img class="menu-logo" src="../icon-512.png"><h1>KT COMPANION</h1><p class="subtitle">Battle Board — sistema de fases</p><div class="menu-grid"><button class="menu-card" onclick="newMatrix()"><strong>MATRIZ NUEVA</strong><span>Crear una secuencia de Despliegue y Turnos.</span><em>+</em></button><button class="menu-card" onclick="saved()"><strong>MATRICES GUARDADAS</strong><span>Abrir y editar cualquier fase guardada.</span><em>▣</em></button></div></main>`}
function newMatrix(){Object.assign(S,{screen:'wizard',step:1,team:null,map:null,critical:null,phase:'despliegue',phaseData:{},objects:[],notes:'',matrixId:null,matrixName:'',undo:[],redo:[]});wizard()}
function wizard(){S.screen='wizard';let body;if(S.step===1)body=`<h3>Selecciona tu Kill Team</h3><div class="choice-grid">${teams.map(t=>`<button class="choice ${S.team?.[0]===t[0]?'selected':''}" onclick='S.team=${JSON.stringify(t)};wizard()'><h3>${t[1]}</h3><p>Equipo provisional de Alpha.</p></button>`).join('')}</div><div class="wizard-actions"><span></span><button class="primary" ${S.team?'':'disabled'} onclick="S.step=2;wizard()">SIGUIENTE →</button></div>`;else if(S.step===2)body=`<h3>Selecciona el mapa</h3><div class="map-grid">${maps.map((m,i)=>`<button class="map-card choice ${S.map?.[0]===m[0]?'selected':''}" onclick='S.map=${JSON.stringify(m)};wizard()'><div class="map-thumb">${mapSvg(i+1)}</div><div class="meta"><b>${m[1]}</b><span>22×30&quot;</span></div></button>`).join('')}</div><div class="wizard-actions"><button onclick="S.step=1;wizard()">← ATRÁS</button><button class="primary" ${S.map?'':'disabled'} onclick="S.step=3;wizard()">SIGUIENTE →</button></div>`;else body=`<h3>Selecciona una operación crítica</h3><p style="color:#8f9699">Ninguna viene seleccionada. Debes elegir una.</p><div class="ops">${ops.map((o,i)=>`<button class="op ${S.critical===i?'selected':''}" onclick="S.critical=${i};wizard()">${i+1}. ${o}</button>`).join('')}</div><div class="wizard-actions"><button onclick="S.step=2;wizard()">← ATRÁS</button><button class="primary" ${S.critical===null?'disabled':''} onclick="openBoard()">CREAR MATRIZ →</button></div>`;app.innerHTML=header()+`<main class="content"><div class="page-title"><div><h2>NUEVA MATRIZ</h2><p>Construye tu planificación.</p></div></div><div class="steps">${['KILL TEAM','MAPA','OPERACIÓN'].map((x,i)=>`<div class="step ${S.step===i+1?'active':''}">${i+1} · ${x}</div>`).join('')}</div><div class="card">${body}</div></main>`}
function mapSvg(n){const r=n===1?[[80,80,220,110],[520,120,160,220],[250,470,190,120],[720,500,150,170]]:n===2?[[100,120,180,210],[400,70,270,100],[690,360,190,220],[250,540,220,100]]:[[70,90,260,100],[390,250,180,180],[700,90,190,150],[90,530,170,150]];return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 733"><rect width="1000" height="733" fill="#99988d"/>${r.map(a=>`<rect x="${a[0]}" y="${a[1]}" width="${a[2]}" height="${a[3]}" rx="8" fill="#50534f"/>`).join('')}<rect x="18" y="18" width="964" height="697" fill="none" stroke="#222" stroke-width="5"/><text x="500" y="370" text-anchor="middle" font-family="Arial" font-size="28" fill="#222" opacity=".3">22 × 30 IN</text></svg>`)}
function image(){return new Promise(resolve=>{const im=new Image();im.onload=()=>resolve(im);im.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(mapSvg(Number(S.map[0].slice(1))))})}
function openBoard(){S.screen='board';S.phase='despliegue';S.objects=[];S.notes='';board()}
function board(){app.innerHTML=header()+`<main class="board-wrap"><div class="board-toolbar"><button class="tool ${S.tool==='drag'?'active':''}" onclick="setTool('drag')">✋ MOVER</button><button class="tool" onclick="setTool('line')">╱</button><button class="tool" onclick="setTool('arrow')">➜</button><button class="tool" onclick="setTool('rect')">□</button><button class="tool" onclick="setTool('circle')">○</button><button class="tool" onclick="setTool('text')">T</button><button class="tool" onclick="tokenMenu()">🔵 FICHA</button><button class="tool" onclick="setTool('ruler')">📐 MEDIR</button><button class="tool" onclick="setTool('temp')">📏 REGLA</button><button class="tool" onclick="styleMenu()">🎨</button><button class="tool" onclick="undo()">↶</button><button class="tool" onclick="redo()">↷</button><span class="toolbar-spacer"></span><button class="tool" onclick="phaseMenu()">${labels[S.phase]} ▾</button><button class="tool" onclick="captureMenu()">📸 GUARDAR FASE</button><button class="tool primary" onclick="saveMatrix()">💾 GUARDAR MATRIZ</button></div><div class="board-area"><div class="canvas-shell"><canvas id="phaseCanvas"></canvas></div></div><div style="padding:8px 14px;background:#111518;border-top:1px solid #30363a"><div style="display:flex;justify-content:space-between;color:#c8c7c0;font-size:12px"><b>📝 NOTAS — ${labels[S.phase]}</b><span>${S.phaseData[S.phase]?'✓ FASE GUARDADA':'FASE NO GUARDADA'}</span></div><textarea id="phaseNotes" style="width:100%;min-height:58px;margin-top:7px;background:#0b0d0f;color:#eee;border:1px solid #343b40;border-radius:5px;padding:9px;resize:vertical" placeholder="Notas de esta fase...">${esc(S.notes)}</textarea></div><div class="delete-zone" style="margin:7px 14px;padding:8px;text-align:center;border:1px dashed #8d1711;color:#e7aaa3;border-radius:5px" ondragover="event.preventDefault()" ondrop="deleteDrop(event)">🗑️ ARRASTRA AQUÍ PARA ELIMINAR</div><div style="height:30px;background:#0d1012;display:flex;align-items:center;justify-content:center;gap:25px"><span class="board-info">22 × 30 PULGADAS</span><span class="board-info">${S.map[1]}</span><span class="board-info">OP: ${ops[S.critical]}</span></div></main>`;setupCanvas()}
function setupCanvas(){canvas=document.getElementById('phaseCanvas');ctx=canvas.getContext('2d');const d=devicePixelRatio||1;canvas.width=1000*d;canvas.height=733*d;ctx.setTransform(d,0,0,d,0,0);image().then(im=>{ctx.drawImage(im,0,0,1000,733);redraw()});canvas.onpointerdown=e=>{start=point(e);if(S.tool==='drag'){selected=hit(start);if(selected){down=true;selected._sx=selected.x??selected.x1;selected._sy=selected.y??selected.y1}return}if(S.tool==='text'){const z=prompt('Texto:');if(z){pushUndo();S.objects.push({t:'text',x:start.x,y:start.y,z,color:S.color,opacity:S.opacity})}redraw();return}down=true;preview=start};canvas.onpointermove=e=>{if(!down)return;const p=point(e);if(selected){moveSelected(p);redraw();return}preview=p;redraw()};canvas.onpointerup=e=>{if(!down)return;const p=point(e);down=false;if(selected){delete selected._sx;delete selected._sy;selected=null;redraw();return}finish(start,p);preview=null;redraw()}}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*1000,y:(e.clientY-r.top)/r.height*733}}
function setTool(t){S.tool=t;selected=null;board()}
function pushUndo(){S.undo.push(JSON.stringify(S.objects));S.redo=[]}
function finish(a,b){if(S.tool==='temp')return;pushUndo();if(['line','arrow','ruler'].includes(S.tool))S.objects.push({t:S.tool,x1:a.x,y1:a.y,x2:b.x,y2:b.y,color:S.color,opacity:S.opacity});else if(S.tool==='rect')S.objects.push({t:'rect',x:a.x,y:a.y,w:b.x-a.x,h:b.y-a.y,color:S.color,opacity:S.opacity});else if(S.tool==='circle')S.objects.push({t:'circle',x:a.x,y:a.y,rx:Math.abs(b.x-a.x),ry:Math.abs(b.y-a.y),color:S.color,opacity:S.opacity});else if(S.tool==='token')S.objects.push({t:'token',x:a.x,y:a.y,r:(S.tokenMm/28)*28,mm:S.tokenMm,color:S.color,opacity:S.opacity})}
function moveSelected(p){const o=selected,dx=p.x-start.x,dy=p.y-start.y;if(['line','arrow','ruler'].includes(o.t)){o.x1+=dx;o.y1+=dy;o.x2+=dx;o.y2+=dy}else{o.x=(o._sx??o.x)+dx;o.y=(o._sy??o.y)+dy}start=p}
function hit(p){for(let i=S.objects.length-1;i>=0;i--){const o=S.objects[i];if(o.t==='token'&&Math.hypot(p.x-o.x,p.y-o.y)<o.r)return o;if(['line','arrow','ruler'].includes(o.t)){const dx=o.x2-o.x1,dy=o.y2-o.y1,t=Math.max(0,Math.min(1,((p.x-o.x1)*dx+(p.y-o.y1)*dy)/(dx*dx+dy*dy||1)));if(Math.hypot(p.x-(o.x1+t*dx),p.y-(o.y1+t*dy))<14)return o}if(o.t==='rect'&&p.x>=Math.min(o.x,o.x+o.w)&&p.x<=Math.max(o.x,o.x+o.w)&&p.y>=Math.min(o.y,o.y+o.h)&&p.y<=Math.max(o.y,o.y+o.h))return o;if(o.t==='circle'&&Math.abs(Math.hypot(p.x-o.x,p.y-o.y)-Math.max(o.rx,o.ry))<14)return o}return null}
function drawObj(o){ctx.save();ctx.globalAlpha=o.opacity??1;ctx.strokeStyle=o.color||'#ef5a16';ctx.fillStyle=o.color||'#ef5a16';ctx.lineWidth=3;if(['line','arrow','ruler'].includes(o.t)){ctx.beginPath();ctx.moveTo(o.x1,o.y1);ctx.lineTo(o.x2,o.y2);ctx.stroke();if(o.t==='arrow'){const q=Math.atan2(o.y2-o.y1,o.x2-o.x1);ctx.beginPath();ctx.moveTo(o.x2,o.y2);ctx.lineTo(o.x2-18*Math.cos(q-.5),o.y2-18*Math.sin(q-.5));ctx.lineTo(o.x2-18*Math.cos(q+.5),o.y2-18*Math.sin(q+.5));ctx.fill()}if(o.t==='ruler')distance(o)}else if(o.t==='rect')ctx.strokeRect(o.x,o.y,o.w,o.h);else if(o.t==='circle'){ctx.beginPath();ctx.ellipse(o.x,o.y,o.rx,o.ry,0,0,Math.PI*2);ctx.stroke()}else if(o.t==='text'){ctx.font='bold 22px Arial';ctx.fillText(o.z,o.x,o.y)}else if(o.t==='token'){ctx.beginPath();ctx.arc(o.x,o.y,o.r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.stroke();ctx.fillStyle='#fff';ctx.font='bold 14px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(o.mm,o.x,o.y)}ctx.restore()}
function distance(o){const inch=Math.hypot(o.x2-o.x1,o.y2-o.y1)/(1000/30);ctx.save();ctx.fillStyle='#111';ctx.font='bold 18px Arial';ctx.textAlign='center';ctx.fillText((Math.round(inch*4)/4)+'"',(o.x1+o.x2)/2,(o.y1+o.y2)/2-8);ctx.restore()}
function redraw(){image().then(im=>{ctx.clearRect(0,0,1000,733);ctx.drawImage(im,0,0,1000,733);S.objects.forEach(drawObj);if(S.tool==='temp'&&start&&preview)drawObj({t:'ruler',x1:start.x,y1:start.y,x2:preview.x,y2:preview.y,color:'#ef5a16',opacity:.8})})}
function undo(){if(S.undo.length){S.redo.push(JSON.stringify(S.objects));S.objects=JSON.parse(S.undo.pop());redraw()}}function redo(){if(S.redo.length){S.undo.push(JSON.stringify(S.objects));S.objects=JSON.parse(S.redo.pop());redraw()}}
function tokenMenu(){app.insertAdjacentHTML('beforeend',`<div class="modal" id="tokenModal"><div class="modal-card"><h2>🔵 FICHA</h2><p>28 mm es el tamaño predeterminado.</p><div class="phase-list">${[25,28,32,40].map(n=>`<button onclick="S.tokenMm=${n};S.tool='token';tokenModal.remove();board()">${n} mm</button>`).join('')}<button onclick="customToken()">PERSONALIZADO</button></div><button onclick="tokenModal.remove()">CANCELAR</button></div></div>`)}
function customToken(){const n=Number(prompt('Tamaño en mm:',S.tokenMm));if(n>0){S.tokenMm=n;S.tool='token';tokenModal.remove();board()}}
function styleMenu(){if(!selected){toast('Activa MOVER y selecciona un objeto.');return}app.insertAdjacentHTML('beforeend',`<div class="modal" id="styleModal"><div class="modal-card"><h2>🎨 COLOR Y OPACIDAD</h2><label>Color <input id="styleColor" type="color" value="${selected.color||'#ef5a16'}"></label><br><br><label>Opacidad <input id="styleOpacity" type="range" min="0" max="100" value="${Math.round((selected.opacity??1)*100)}"></label><div class="wizard-actions"><button onclick="styleModal.remove()">CANCELAR</button><button class="primary" onclick="selected.color=styleColor.value;selected.opacity=Number(styleOpacity.value)/100;styleModal.remove();redraw()">APLICAR</button></div></div></div>`)}
function phaseMenu(){saveNotes();app.insertAdjacentHTML('beforeend',`<div class="modal" id="phaseModal"><div class="modal-card"><h2>FASES DE LA MATRIZ</h2><p style="color:#9da3a6">Las fases guardadas se pueden abrir, editar y volver a guardar. Una fase nueva conserva el dibujo actual como punto de partida.</p><div class="phase-list">${phases.map(p=>`<button class="phase ${S.phase===p?'selected':''}" onclick="openPhase('${p}')">${labels[p]} ${S.phaseData[p]?'✓ GUARDADA':''}</button>`).join('')}</div><button onclick="phaseModal.remove()">CERRAR</button></div></div>`)}
function openPhase(p){saveNotes();phaseModal.remove();if(S.phaseData[p]){S.objects=copy(S.phaseData[p].objects);S.notes=S.phaseData[p].notes||'';toast(labels[p]+' cargado para editar')}else{S.notes='';toast(labels[p]+' nuevo: continúa desde el estado actual')}S.phase=p;S.undo=[];S.redo=[];board()}
function captureMenu(){saveNotes();app.insertAdjacentHTML('beforeend',`<div class="modal" id="captureModal"><div class="modal-card"><h2>📸 GUARDAR / SOBRESCRIBIR</h2><p style="color:#9da3a6">La captura se guarda como una instantánea. El tablero de trabajo NO cambia.</p><div class="phase-list">${phases.map(p=>`<button class="phase ${S.phase===p?'selected':''}" onclick="S.phase='${p}';captureModal.remove();board()">${labels[p]} ${S.phaseData[p]?'✓':''}</button>`).join('')}</div><div class="wizard-actions"><button onclick="captureModal.remove()">CANCELAR</button><button class="primary" onclick="savePhase()">GUARDAR FASE ACTUAL</button></div></div></div>`)}
function saveNotes(){const n=document.getElementById('phaseNotes');if(n)S.notes=n.value}
function savePhase(){saveNotes();S.phaseData[S.phase]={objects:copy(S.objects),notes:S.notes,image:captureImage()};captureModal.remove();board();toast(labels[S.phase]+' guardado. Puedes seguir trabajando sobre el tablero actual.')}
function captureImage(){const out=document.createElement('canvas');out.width=1200;out.height=950;const q=out.getContext('2d');q.fillStyle='#fff';q.fillRect(0,0,1200,950);q.drawImage(canvas,0,0,1200,880);q.fillStyle='#111';q.font='bold 21px Arial';q.fillText('NOTAS — '+labels[S.phase],35,915);q.font='17px Arial';q.fillText(S.notes||'',35,940);return out.toDataURL('image/png')}
function deleteDrop(e){e.preventDefault();const p=point(e),o=hit(p);if(o){pushUndo();S.objects.splice(S.objects.indexOf(o),1);redraw();toast('Objeto eliminado')}}
function saveMatrix(){saveNotes();const name=S.matrixName||prompt('Nombre de la matriz:','Matriz KT')||'Matriz KT';S.matrixName=name;const a=JSON.parse(localStorage.ktMatrices||'[]');const data={id:S.matrixId||Date.now(),name,team:S.team,map:S.map,critical:S.critical,phaseData:S.phaseData,current:{phase:S.phase,objects:copy(S.objects),notes:S.notes},created:S.created||new Date().toISOString(),updated:new Date().toISOString()};const i=a.findIndex(m=>m.id===data.id);if(i>=0)a[i]=data;else{S.matrixId=data.id;a.push(data)}localStorage.ktMatrices=JSON.stringify(a);toast(i>=0?'Matriz actualizada':'Matriz guardada');setTimeout(saved,350)}
function saved(){S.screen='saved';const a=JSON.parse(localStorage.ktMatrices||'[]');app.innerHTML=header()+`<main class="content"><div class="page-title"><div><h2>MATRICES GUARDADAS</h2><p>Al abrir una matriz podrás acceder a Despliegue y Turnos 1–4.</p></div><button class="primary" onclick="newMatrix()">+ MATRIZ NUEVA</button></div><div class="save-list">${a.length?a.slice().reverse().map(m=>`<div class="card saved"><div><strong>${esc(m.name)}</strong><small>${m.team?.[1]||''} · ${m.map?.[1]||''}<br>${Object.keys(m.phaseData||{}).map(p=>labels[p]).join(' · ')||'Sin fases guardadas'}</small></div><button onclick="loadMatrix(${m.id})">ABRIR Y EDITAR</button></div>`).join(''):'<div class="card">No hay matrices guardadas todavía.</div>'}</div></main>`}
function loadMatrix(id){const m=JSON.parse(localStorage.ktMatrices||'[]').find(q=>q.id===id);if(!m)return;Object.assign(S,{screen:'board',team:m.team,map:m.map,critical:m.critical,phaseData:m.phaseData||{},matrixId:m.id,matrixName:m.name,phase:m.current?.phase||'despliegue',objects:copy(m.current?.objects||[]),notes:m.current?.notes||'',undo:[],redo:[]});board();toast('Matriz abierta: puedes editar cualquier fase')}
function toast(t){const d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
home();